from __future__ import annotations

from dataclasses import asdict
from pathlib import Path
import hashlib
import json
import os
import shutil
import struct
import subprocess
import tempfile
from datetime import datetime, timezone
import numpy as np
import colour

from ..core.color import delta_e76, delta_e2000, summarize
from ..core.external import external_tool_path, run_external
from ..core.models import ErrorSummary, PatchError, ProfileBuildResult, Recipe, SampleSet, ValidationResult
from ..core.models import read_json, write_json
from ..version import __version__


D50_XY = np.asarray(colour.CCS_ILLUMINANTS["CIE 1931 2 Degree Standard Observer"]["D50"], dtype=np.float64)
D50_XYZ = np.asarray(colour.xy_to_XYZ(D50_XY), dtype=np.float64)
ARGYLL_CACHE_DIR_ENV = "PROBRAW_ARGYLL_CACHE_DIR"
ARGYLL_COLPROF_CACHE_ENV = "PROBRAW_ARGYLL_COLPROF_CACHE"
_COLPROF_CACHE_SCHEMA = "colprof-cache-v1"
_ARGYLL_MODEL_FLAGS = {
    "-as": "argyll_shaper_matrix",
    "-ag": "argyll_gamma_matrix",
    "-am": "argyll_matrix",
    "-al": "argyll_lab_clut",
    "-ax": "argyll_xyz_clut",
}


def build_profile(
    samples: SampleSet,
    recipe: Recipe,
    out_icc: Path,
    camera_model: str | None,
    lens_model: str | None,
) -> ProfileBuildResult:
    measured_rgb, reference_xyz, reference_lab, patch_ids = _samples_to_arrays(samples)

    matrix, matrix_summary, matrix_patch_errors = _diagnostic_matrix_fit(
        measured_rgb=measured_rgb,
        reference_xyz=reference_xyz,
        reference_lab=reference_lab,
        patch_ids=patch_ids,
    )

    out_icc.parent.mkdir(parents=True, exist_ok=True)

    engine_requested = (recipe.profile_engine or "argyll").lower()
    if engine_requested != "argyll":
        raise RuntimeError(
            f"profile_engine no soportado: {recipe.profile_engine}. "
            "Este proyecto usa exclusivamente ArgyllCMS ('argyll')."
        )

    _build_profile_with_argyll(
        out_icc=out_icc,
        measured_rgb=measured_rgb,
        reference_lab=reference_lab,
        patch_ids=patch_ids,
        description=f"ProbRAW {samples.chart_name} {samples.chart_version}",
        extra_args=recipe.argyll_colprof_args,
    )

    engine_used = "argyll"
    engine_warning = None
    profile_model, profile_model_flag = _argyll_profile_model(recipe.argyll_colprof_args)

    if not out_icc.exists():
        raise RuntimeError("ArgyllCMS no genero el perfil ICC esperado.")

    predicted_lab = _lookup_lab_with_icc(out_icc, measured_rgb)
    summary, patch_errors = _profile_error_summary(
        predicted_lab=predicted_lab,
        reference_lab=reference_lab,
        patch_ids=patch_ids,
    )

    profile_json_path = out_icc.with_suffix(".profile.json")
    metadata = {
        "camera_model": camera_model,
        "lens_model": lens_model,
        "illuminant": samples.illuminant,
        "chart_name": samples.chart_name,
        "chart_version": samples.chart_version,
        "algorithm_version": __version__,
        "profile_engine_requested": engine_requested,
        "profile_engine_used": engine_used,
        "engine_warning": engine_warning,
        "profile_model": profile_model,
        "argyll_profile_model_flag": profile_model_flag,
        "recipe": asdict(recipe),
        # Diagnostic matrix only. The reported DeltaE metrics below are computed
        # from the ICC actually generated by ArgyllCMS, not from this fit.
        "matrix_camera_to_xyz": matrix.tolist(),
        "trc_gamma": 1.0,
        "diagnostic_matrix_error_summary": asdict(matrix_summary),
        "diagnostic_matrix_patch_errors": [asdict(error) for error in matrix_patch_errors],
        "error_summary": asdict(summary),
    }
    write_json(profile_json_path, metadata)

    return ProfileBuildResult(
        output_icc=str(out_icc),
        output_profile_json=str(profile_json_path),
        model=profile_model,
        matrix_camera_to_xyz=matrix.tolist(),
        trc_gamma=1.0,
        error_summary=summary,
        patch_errors=patch_errors,
        metadata=metadata,
    )


def _argyll_profile_model(args: list[str] | None) -> tuple[str, str | None]:
    effective_args = list(args or [])
    if not effective_args:
        env_args = os.environ.get("ICC_ARGYLL_COLPROF_ARGS", "").strip()
        effective_args = env_args.split() if env_args else ["-qm", "-as", "-u", "-R"]
    for arg in effective_args:
        if arg in _ARGYLL_MODEL_FLAGS:
            return _ARGYLL_MODEL_FLAGS[arg], arg
    return "argyll_custom", None


def _diagnostic_matrix_fit(
    *,
    measured_rgb: np.ndarray,
    reference_xyz: np.ndarray,
    reference_lab: np.ndarray,
    patch_ids: list[str],
) -> tuple[np.ndarray, ErrorSummary, list[PatchError]]:
    matrix, *_ = np.linalg.lstsq(measured_rgb, reference_xyz, rcond=None)
    predicted_lab = colour.XYZ_to_Lab(measured_rgb @ matrix, illuminant=D50_XY)
    summary, patch_errors = _profile_error_summary(
        predicted_lab=predicted_lab,
        reference_lab=reference_lab,
        patch_ids=patch_ids,
    )
    return matrix, summary, patch_errors


def _profile_error_summary(
    *,
    predicted_lab: np.ndarray,
    reference_lab: np.ndarray,
    patch_ids: list[str],
) -> tuple[ErrorSummary, list[PatchError]]:
    de76 = np.asarray(delta_e76(predicted_lab, reference_lab), dtype=np.float64)
    de00 = np.asarray(delta_e2000(predicted_lab, reference_lab), dtype=np.float64)

    patch_errors = [
        PatchError(
            patch_id=pid,
            delta_e76=float(a),
            delta_e2000=float(b),
            reference_lab=_lab_triplet(reference),
            profile_lab=_lab_triplet(predicted),
        )
        for pid, a, b, reference, predicted in zip(
            patch_ids,
            de76,
            de00,
            reference_lab,
            predicted_lab,
            strict=True,
        )
    ]

    s76 = summarize(de76)
    s00 = summarize(de00)
    summary = ErrorSummary(
        mean_delta_e76=s76["mean"],
        median_delta_e76=s76["median"],
        p95_delta_e76=s76["p95"],
        max_delta_e76=s76["max"],
        mean_delta_e2000=s00["mean"],
        median_delta_e2000=s00["median"],
        p95_delta_e2000=s00["p95"],
        max_delta_e2000=s00["max"],
    )
    return summary, patch_errors


def validate_profile(samples: SampleSet, profile_path: Path) -> ValidationResult:
    if not profile_path.exists():
        raise FileNotFoundError(f"No existe perfil ICC: {profile_path}")

    measured_rgb, _reference_xyz, reference_lab, patch_ids = _samples_to_arrays(samples)
    predicted_lab = _lookup_lab_with_icc(profile_path, measured_rgb)

    de76 = np.asarray(delta_e76(predicted_lab, reference_lab), dtype=np.float64)
    de00 = np.asarray(delta_e2000(predicted_lab, reference_lab), dtype=np.float64)

    patch_errors = [
        PatchError(
            patch_id=pid,
            delta_e76=float(a),
            delta_e2000=float(b),
            reference_lab=_lab_triplet(reference),
            profile_lab=_lab_triplet(predicted),
        )
        for pid, a, b, reference, predicted in zip(
            patch_ids,
            de76,
            de00,
            reference_lab,
            predicted_lab,
            strict=True,
        )
    ]

    s76 = summarize(de76)
    s00 = summarize(de00)
    summary = ErrorSummary(
        mean_delta_e76=s76["mean"],
        median_delta_e76=s76["median"],
        p95_delta_e76=s76["p95"],
        max_delta_e76=s76["max"],
        mean_delta_e2000=s00["mean"],
        median_delta_e2000=s00["median"],
        p95_delta_e2000=s00["p95"],
        max_delta_e2000=s00["max"],
    )

    return ValidationResult(profile_path=str(profile_path), error_summary=summary, patch_errors=patch_errors)


def _lab_triplet(values: np.ndarray) -> list[float]:
    lab = np.asarray(values, dtype=np.float64).reshape(-1)
    if lab.size < 3:
        return [0.0, 0.0, 0.0]
    return [float(lab[0]), float(lab[1]), float(lab[2])]


def _lookup_lab_with_icc(profile_path: Path, measured_rgb: np.ndarray) -> np.ndarray:
    xicclu = external_tool_path("xicclu") or external_tool_path("icclu")
    if xicclu is None:
        raise RuntimeError("No se puede validar ICC: 'xicclu'/'icclu' no esta disponible en PATH.")

    rgb = np.asarray(measured_rgb, dtype=np.float64)
    if rgb.ndim != 2 or rgb.shape[1] != 3:
        raise RuntimeError("measured_rgb debe tener forma Nx3")

    stdin = "\n".join(" ".join(f"{float(v):.10g}" for v in row) for row in rgb) + "\n"
    cmd = [
        xicclu,
        "-v0",
        "-ff",
        "-ir",
        "-pl",
        str(profile_path),
    ]
    proc = run_external(cmd, input=stdin, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    if proc.returncode != 0:
        stderr_tail = (proc.stderr or proc.stdout)[-500:]
        raise RuntimeError(f"Fallo validando ICC con {Path(xicclu).name}: {stderr_tail}")

    rows: list[list[float]] = []
    for line in proc.stdout.splitlines():
        line = line.strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) < 3:
            continue
        try:
            rows.append([float(parts[0]), float(parts[1]), float(parts[2])])
        except ValueError as exc:
            raise RuntimeError(f"Salida inesperada de {Path(xicclu).name}: {line}") from exc

    if len(rows) != len(rgb):
        raise RuntimeError(
            f"{Path(xicclu).name} devolvio {len(rows)} muestras Lab para {len(rgb)} entradas RGB"
        )

    return np.asarray(rows, dtype=np.float64)


def load_profile_model(profile_path: Path) -> dict:
    sidecar = profile_path.with_suffix(".profile.json")
    if not sidecar.exists():
        raise FileNotFoundError(f"No existe sidecar: {sidecar}")
    return read_json(sidecar)


def write_samples_cgats(samples: SampleSet, out_path: Path) -> None:
    measured_rgb, _reference_xyz, reference_lab, patch_ids = _samples_to_arrays(samples)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    _write_ti3(
        out_path,
        measured_rgb,
        reference_lab,
        patch_ids,
        descriptor=f"ProbRAW {samples.chart_name} {samples.chart_version} samples",
        chart_name=samples.chart_name,
        chart_version=samples.chart_version,
        illuminant=samples.illuminant,
        strategy=samples.strategy,
    )


def _samples_to_arrays(samples: SampleSet):
    patch_ids: list[str] = []
    measured: list[list[float]] = []
    reference_xyz: list[list[float]] = []
    reference_lab: list[list[float]] = []

    for s in samples.samples:
        if s.reference_lab is None:
            continue
        patch_ids.append(s.patch_id)
        measured.append([float(v) for v in s.measured_rgb])
        lab = np.asarray(s.reference_lab, dtype=np.float64)
        xyz = colour.Lab_to_XYZ(lab, illuminant=D50_XY)
        reference_xyz.append([float(x) for x in xyz])
        reference_lab.append([float(v) for v in lab])

    if not measured:
        raise RuntimeError("No hay parches con reference_lab para construir/validar perfil")

    return (
        np.asarray(measured, dtype=np.float64),
        np.asarray(reference_xyz, dtype=np.float64),
        np.asarray(reference_lab, dtype=np.float64),
        patch_ids,
    )


def _build_profile_with_argyll(
    out_icc: Path,
    measured_rgb: np.ndarray,
    reference_lab: np.ndarray,
    patch_ids: list[str],
    description: str,
    extra_args: list[str] | None,
) -> None:
    colprof = external_tool_path("colprof")
    if colprof is None:
        raise RuntimeError("colprof no esta en PATH")

    args = [colprof, "-v", "-D", description]
    env_args = os.environ.get("ICC_ARGYLL_COLPROF_ARGS", "").strip()
    if extra_args:
        args.extend(extra_args)
    elif env_args:
        args.extend(env_args.split())
    else:
        args.extend(["-qm", "-as", "-u", "-R"])

    cache_path: Path | None = None
    if _colprof_cache_enabled():
        cache_path = _colprof_cache_path(
            colprof=colprof,
            args=args,
            measured_rgb=measured_rgb,
            reference_lab=reference_lab,
            patch_ids=patch_ids,
            description=description,
        )
        cached_bytes = _read_colprof_cache(cache_path)
        if cached_bytes is not None:
            out_icc.parent.mkdir(parents=True, exist_ok=True)
            out_icc.write_bytes(cached_bytes)
            return

    with tempfile.TemporaryDirectory(prefix="probraw_argyll_") as tmp:
        tmpdir = Path(tmp)
        base = tmpdir / "camera_profile"
        ti3 = base.with_suffix(".ti3")
        _write_ti3(ti3, measured_rgb, reference_lab, patch_ids)

        args.append(base.stem)

        proc = run_external(args, cwd=tmpdir, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        if proc.returncode != 0:
            raise RuntimeError(f"colprof retorno {proc.returncode}: {proc.stdout[-500:]}")

        produced = base.with_suffix(".icc")
        if not produced.exists():
            produced = base.with_suffix(".icm")
        if not produced.exists():
            raise RuntimeError("colprof no produjo fichero .icc/.icm")

        shutil.copy2(produced, out_icc)
        if cache_path is not None:
            _write_colprof_cache(cache_path, produced.read_bytes())


def _colprof_cache_enabled() -> bool:
    return _read_env_bool(ARGYLL_COLPROF_CACHE_ENV, default=True)


def _read_env_bool(name: str, *, default: bool) -> bool:
    raw = os.environ.get(name, "").strip().lower()
    if not raw:
        return bool(default)
    if raw in {"1", "true", "yes", "on"}:
        return True
    if raw in {"0", "false", "no", "off"}:
        return False
    return bool(default)


def _argyll_cache_dir() -> Path:
    configured = os.environ.get(ARGYLL_CACHE_DIR_ENV, "").strip()
    if configured:
        return Path(configured).expanduser() / "colprof"
    return Path.home() / ".probraw" / "argyll_cache" / "colprof"


def _colprof_cache_path(
    *,
    colprof: str,
    args: list[str],
    measured_rgb: np.ndarray,
    reference_lab: np.ndarray,
    patch_ids: list[str],
    description: str,
) -> Path:
    key = _colprof_cache_key(
        colprof=colprof,
        args=args,
        measured_rgb=measured_rgb,
        reference_lab=reference_lab,
        patch_ids=patch_ids,
        description=description,
    )
    return _argyll_cache_dir() / f"{key}.icc"


def _colprof_cache_key(
    *,
    colprof: str,
    args: list[str],
    measured_rgb: np.ndarray,
    reference_lab: np.ndarray,
    patch_ids: list[str],
    description: str,
) -> str:
    measured = np.ascontiguousarray(np.asarray(measured_rgb, dtype=np.float64))
    reference = np.ascontiguousarray(np.asarray(reference_lab, dtype=np.float64))
    payload = {
        "schema": _COLPROF_CACHE_SCHEMA,
        "tool": _colprof_binary_fingerprint(colprof),
        "args": [str(part) for part in args],
        "description": str(description),
        "measured_shape": list(measured.shape),
        "reference_shape": list(reference.shape),
        "patch_ids": [str(pid) for pid in patch_ids],
    }
    h = hashlib.sha256()
    h.update(json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8"))
    h.update(measured.tobytes(order="C"))
    h.update(reference.tobytes(order="C"))
    return h.hexdigest()


def _colprof_binary_fingerprint(colprof: str) -> str:
    try:
        path = Path(colprof).expanduser().resolve()
        st = path.stat()
        return f"{path}|{st.st_mtime_ns}|{st.st_size}"
    except Exception:
        return str(colprof)


def _read_colprof_cache(path: Path) -> bytes | None:
    try:
        if not path.exists() or not path.is_file():
            return None
        payload = path.read_bytes()
        if len(payload) < 128:
            return None
        return payload
    except Exception:
        return None


def _write_colprof_cache(path: Path, payload: bytes) -> None:
    try:
        target = Path(path)
        target.parent.mkdir(parents=True, exist_ok=True)
        temp = target.with_name(f"{target.name}.tmp")
        temp.write_bytes(payload)
        os.replace(temp, target)
    except Exception:
        return


def _write_ti3(
    path: Path,
    measured_rgb: np.ndarray,
    reference_lab: np.ndarray,
    patch_ids: list[str],
    *,
    descriptor: str = "ProbRAW chart samples",
    chart_name: str | None = None,
    chart_version: str | None = None,
    illuminant: str | None = None,
    strategy: str | None = None,
) -> None:
    lines: list[str] = []
    lines.append('CTI3')
    lines.append('DESCRIPTOR "{}"'.format(_cgats_text(descriptor)))
    lines.append('ORIGINATOR "ProbRAW"')
    lines.append('CREATED "{}"'.format(datetime.now(timezone.utc).isoformat()))
    for key, value in {
        "CHART_NAME": chart_name,
        "CHART_VERSION": chart_version,
        "ILLUMINANT": illuminant,
        "SAMPLING_STRATEGY": strategy,
    }.items():
        if value:
            lines.append(f'KEYWORD "{key}"')
            lines.append(f'{key} "{_cgats_text(str(value))}"')
    lines.append('KEYWORD "DEVICE_CLASS"')
    lines.append('DEVICE_CLASS "INPUT"')
    lines.append('KEYWORD "COLOR_REP"')
    lines.append('COLOR_REP "LAB_RGB"')
    lines.append('NUMBER_OF_FIELDS 7')
    lines.append('BEGIN_DATA_FORMAT')
    lines.append('SAMPLE_ID LAB_L LAB_A LAB_B RGB_R RGB_G RGB_B')
    lines.append('END_DATA_FORMAT')
    lines.append(f'NUMBER_OF_SETS {len(patch_ids)}')
    lines.append('BEGIN_DATA')

    for pid, rgb, lab in zip(patch_ids, measured_rgb, reference_lab, strict=True):
        rr, gg, bb = [float(v) * 100.0 for v in rgb]
        ll, aa, bb_lab = [float(v) for v in lab]
        lines.append(f'{pid} {ll:.6f} {aa:.6f} {bb_lab:.6f} {rr:.6f} {gg:.6f} {bb:.6f}')

    lines.append('END_DATA')
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def _cgats_text(text: str) -> str:
    return text.replace("\\", "/").replace('"', "'").encode("ascii", "ignore").decode("ascii")


def build_matrix_shaper_icc(description: str, matrix_camera_to_xyz: np.ndarray, gamma: float) -> bytes:
    matrix = np.asarray(matrix_camera_to_xyz, dtype=np.float64)
    if matrix.shape != (3, 3):
        raise ValueError("matrix_camera_to_xyz debe ser 3x3")

    tags: dict[bytes, bytes] = {
        b"wtpt": _xyz_type(D50_XYZ),
        b"rXYZ": _xyz_type(matrix[:, 0]),
        b"gXYZ": _xyz_type(matrix[:, 1]),
        b"bXYZ": _xyz_type(matrix[:, 2]),
        b"rTRC": _curve_type_gamma(gamma),
        b"gTRC": _curve_type_gamma(gamma),
        b"bTRC": _curve_type_gamma(gamma),
        b"cprt": _text_type("Generated by ProbRAW"),
        b"desc": _desc_type(description),
    }

    table_entries: list[tuple[bytes, int, int]] = []
    body = bytearray()

    offset = 128 + 4 + len(tags) * 12
    for sig, data in tags.items():
        pad = (4 - (offset % 4)) % 4
        if pad:
            body.extend(b"\x00" * pad)
            offset += pad
        table_entries.append((sig, offset, len(data)))
        body.extend(data)
        offset += len(data)

    profile_size = 128 + 4 + len(tags) * 12 + len(body)
    header = _icc_header(profile_size)

    tag_table = bytearray()
    tag_table.extend(struct.pack(">I", len(tags)))
    for sig, off, size in table_entries:
        tag_table.extend(sig)
        tag_table.extend(struct.pack(">II", off, size))

    return bytes(header + tag_table + body)


def _icc_header(size: int) -> bytearray:
    h = bytearray(128)
    now = datetime.now(timezone.utc)
    struct.pack_into(">I", h, 0, size)
    h[4:8] = b"pyIC"
    struct.pack_into(">I", h, 8, 0x02400000)
    h[12:16] = b"mntr"
    h[16:20] = b"RGB "
    h[20:24] = b"XYZ "
    struct.pack_into(">6H", h, 24, now.year, now.month, now.day, now.hour, now.minute, now.second)
    h[36:40] = b"acsp"
    h[40:44] = b"APPL"
    struct.pack_into(">I", h, 44, 0)
    h[48:52] = b"    "
    h[52:56] = b"    "
    struct.pack_into(">Q", h, 56, 0)
    struct.pack_into(">I", h, 64, 0)
    struct.pack_into(">iii", h, 68, _s15f16(D50_XYZ[0]), _s15f16(D50_XYZ[1]), _s15f16(D50_XYZ[2]))
    h[80:84] = b"pyIC"
    return h


def _xyz_type(xyz: np.ndarray) -> bytes:
    x, y, z = [float(v) for v in xyz]
    payload = bytearray()
    payload.extend(b"XYZ ")
    payload.extend(b"\x00\x00\x00\x00")
    payload.extend(struct.pack(">iii", _s15f16(x), _s15f16(y), _s15f16(z)))
    return bytes(payload)


def _curve_type_gamma(gamma: float) -> bytes:
    g = max(0.01, float(gamma))
    u8f8 = int(round(g * 256.0))
    payload = bytearray()
    payload.extend(b"curv")
    payload.extend(b"\x00\x00\x00\x00")
    payload.extend(struct.pack(">I", 1))
    payload.extend(struct.pack(">H", u8f8))
    return bytes(payload)


def _text_type(text: str) -> bytes:
    payload = bytearray()
    payload.extend(b"text")
    payload.extend(b"\x00\x00\x00\x00")
    payload.extend(text.encode("ascii", "ignore") + b"\x00")
    return bytes(payload)


def _desc_type(text: str) -> bytes:
    ascii_text = text.encode("ascii", "ignore")[:200]
    payload = bytearray()
    payload.extend(b"desc")
    payload.extend(b"\x00\x00\x00\x00")
    payload.extend(struct.pack(">I", len(ascii_text) + 1))
    payload.extend(ascii_text + b"\x00")
    payload.extend(struct.pack(">I", 0))
    payload.extend(struct.pack(">I", 0))
    payload.extend(struct.pack(">H", 0))
    payload.extend(struct.pack(">B", 0))
    payload.extend(b"\x00" * 67)
    return bytes(payload)


def _s15f16(value: float) -> int:
    v = int(round(float(value) * 65536.0))
    if v > 0x7FFFFFFF:
        v = 0x7FFFFFFF
    if v < -0x80000000:
        v = -0x80000000
    return v
